//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingPolicy.TestClient.TestService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TrackingPolicy.TestServer/ITestService", ConfigurationName="TrackingPolicy.TestClient.TestService.ITestService")]
    [TrackingPolicy.ServiceModel.Client.TrackingContractBehaviorAttribute()]
    public interface ITestService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TrackingPolicy.TestServer/ITestService/ITestService/Ping", ReplyAction="http://TrackingPolicy.TestServer/ITestService/ITestService/PingResponse")]
        string Ping(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TrackingPolicy.TestServer/ITestService/ITestService/Ping", ReplyAction="http://TrackingPolicy.TestServer/ITestService/ITestService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : TrackingPolicy.TestClient.TestService.ITestService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<TrackingPolicy.TestClient.TestService.ITestService>, TrackingPolicy.TestClient.TestService.ITestService
    {
        
        public TestServiceClient()
        {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string Ping(string text)
        {
            return base.Channel.Ping(text);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string text)
        {
            return base.Channel.PingAsync(text);
        }
    }
}
